apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cloud-native-spring-project/dispatcher-service/k8s?ref=606936e840104851db5a3812a14e3894a61dfc89

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/cloud-native-spring-project/dispatcher-service
  newTag: 606936e840104851db5a3812a14e3894a61dfc89

replicas:
- count: 1
  name: dispatcher-service
