apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - github.com/cloud-native-spring-project/edge-service/k8s?ref=main

patches:
    -   path: patch-env.yml


configMapGenerator:
    -   behavior: merge
        files:
            - application-staging.yml
        name: edge-config

images:
    -   name: edge-service
        newName: ghcr.io/cloud-native-spring-project/edge-service
        newTag: latest

replicas:
    -   count: 2
        name: edge-service
